language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - jspm_packages
before_script:
  - yarn run build
script:
  - yarn run spellcheck
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "./build"
  on:
    branch: master
